### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by mdnaif** [harithsa/Placement-Management-System#3]
The notification feature doesn't seem to be working, please address the issue. The coding indicates that there is a separate database for notifications but the database file isn't included and also there is no code to retrieve the notifications in other profilers like student's read messages feature. Thanks in advance.

**Comment by theharithsa** [comment]
Thank you for notifying me that. I am waiting for someone to help with it. Since this project is too old, I wanted to do it with complete change in platform.

**Comment by mdnaif** [comment]
Thank you for the response. If I do code for it, I’ll fork it with the update. Thank you.

**Comment by Akhilesh786** [comment]
In database placement file is missing

**Comment by theharithsa** [comment]
Placement file is not there. You need to create a DB or table name with that and import all the queries from .sql file to your phpmyadmin
